### ISSUE TITLE
Restrict non-AWS service access from the IoT Gateway via the VPN connection

### ISSUE THREAD

**Issue by gemmerton** [awslabs/iot-static-ip-endpoints#1]
**Is your feature request related to a problem? Please describe.**
The solution works, but in it's current form allows the IoT Gateway to access any internet based hosts, so thinking of potential security exposures it grants open access from inside the customer network well beyond the connectivity required for IoT operation

**Describe the feature you'd like**
I would like a prescribed solution that limits the connectivity through the VPN to only the AWS services required to operate an AWS IoT solution.  Specifically preventing access (via the VPN) for the IoT device/Core to potentially malicious hosts on the internet.  In an ideal world the any solution should not introduce further overhead in needing to scale infrastructure from a customer perspective.

**Additional context**

**Comment by gadams999** [comment]
Hi @gemmerton ,

Sorry for the delay, realized we didn't have a notification forwarder on the repo. Thanks for testing and using the solution.

We'll get back to you regarding this in the next couple of days.

**Comment by gemmerton** [comment]
This can probably be closed (from my perspective) based on release of VPC Endpoints for IoT-Core

**Comment by gadams999** [comment]
No resolution needed.
